name: viral
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  auto_size_text: ^2.1.0
  intl: ^0.16.1
  charts_flutter: ^0.9.0
  date_range_picker: ^1.0.6
  cloud_firestore: ^0.14.0
  palette_generator: ^0.2.3
  simple_animations: ^2.4.0
  flutter_credit_card: ^0.1.3
  http: ^0.12.1
  progress_dialog: ^1.2.4
  path: ^1.6.4
  shared_preferences: ^0.5.7+3
  image_picker: ^0.6.7+3
  flutter_spinkit: ^4.1.2
  flutter_auth_buttons: ^0.8.0
  firebase_auth: ^0.18.0
  firebase_core: ^0.5.0
  provider: ^4.3.1
  uuid: ^2.2.0
  firebase_storage: ^4.0.0
  google_sign_in: ^4.0.4
  carousel_pro: ^1.0.0
  searchable_dropdown: ^1.1.3
  multi_image_picker: ^4.6.9
  flutter_paystack: ^1.0.3+1
  font_awesome_flutter: ^8.8.1
  flutter_launcher_icons:
  international_phone_input: ^1.0.4
  google_fonts: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: 'assets/viral.png'
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
